#!/usr/bin/env bash
# Bash script to install and configure Nginx web server on Ubuntu
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx start
