#!/usr/bin/env bash
# Update package list and install nginx

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\\n\\tlocation /redirect_me {\\n\\t\\treturn 301 https://www.youtube.com/watch?v=CDdvReNKKuk;\\n\\t}"
sudo sed -i "s#server_name _;#$string_for_replacement#" /etc/nginx/sites-enabled/default

sudo service nginx restart

