#!/usr/bin/env bash

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

# Add a location block for /redirect_me with a 301 permanent redirect
sed -i '/server_name _;/a\\location /redirect_me {\return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
