#!/usr/bin/env bash
# Configure Nginx with custom HTTP response header
server_name=$(hostname)
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une error_page" > /usr/share/nginx/html/custom_404.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=CDdvReNKKuk;
    }

    add_header X-Served-By ${server_name};
	
}
" > /etc/nginx/sites-enabled/default

sudo systemctl restart nginx
