#!/usr/bin/env bash
# Install your load balancer
# installs and configures HAproxy with a round-robin algorithm
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend cas_front
	 bind *:80
	 mode http
	 default_backend cas_back

backend cas_back
	balance roundrobin
	server 404407-web-01 54.160.75.51
	server 404407-web-02 52.3.255.57
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
