#!/usr/bin/env bash
# This Bash script displays numbers from 1 to 100 with specific conditions:
# - Displays "FizzBuzz" when the number is a multiple of both 3 and 5
# - Displays "Fizz" when the number is a multiple of 3
# - Displays "Buzz" when the number is a multiple of 5
# - Otherwise, displays the number itself in a list format.

for a in {1..100}
do
  if (( a % 3 == 0 && a % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( a % 3 == 0 ))
  then
    echo "Fizz"
  elif (( a % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$a"
  fi
done
