#!/usr/bin/env bash
# This Bash script displays the content of the /etc/passwd file.
# It extracts and displays the username, user ID, and home directory path for each user.
# If the file does not exist, it provides an appropriate message.

passwd_file="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$passwd_file"
