#!/usr/bin/env bash
# # This Bash script displays user information parsed from the /etc/passwd file.
# It extracts and formats the username, group ID, home directory, shell, password, and user information for each user.
# If the /etc/passwd file does not exist, it provides an appropriate message

passwd_file="/etc/passwd"
f1=""
f2=""
f3=""
while IFS= read -r line
do
    f1="$(echo "$line" | cut -d":" -f1)"
    f2="$(echo "$line" | cut -d":" -f4)"
    f3="$(echo "$line" | cut -d":" -f6)"
    f4="$(echo "$line" | cut -d":" -f7)"
    f5="$(echo "$line" | cut -d":" -f3)"
    f6="$(echo "$line" | cut -d":" -f2)"
    f7="$(echo "$line" | cut -d":" -f5)"
    echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$passwd_file"
