#!/usr/bin/env bash
# Group visitors by IP and HTTP status code, count occurrences, and sort.
# Display data in descending order as: OCCURRENCE_NUMBER IP HTTP_CODE.

log_file="apache-access.log"
awk -F' ' '{ print $1, $9}' $log_file | sort | uniq -c|sort -nr
