#!/usr/bin/env bash
# Display "Best School" 10 times; on the 9th iteration, add "Hi" on a new line

counter=1

while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done

