#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
# It displays hours from 0 to 12 and minutes from 1 to 59.
# Note: The output is limited to the first 70 lines using the head command.

hours=0

while [ $hours -le 12 ]
do
  echo "Hours: $hours"
  minutes=1
  while [ $minutes -le 59 ]
  do
    echo "$minutes"
    (( minutes++ ))
  done
  (( hours++ ))
done
