#!/usr/bin/env bash
# This Bash script provides information about the school file.
# It checks if the file exists and, if so, whether it is empty or a regular file.
# It then prints appropriate messages based on the checks

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
